### ISSUE TITLE
"Meta not found" is a confusing error message

### ISSUE THREAD

**Issue by schuster** [nanopass/nanopass-framework-racket#5]
The error "meta not found" seems to mean that an escaped variable in a pattern does not match any known non-terminal. See https://gist.github.com/schuster/f8898adb8788a77973ec for a simple example.

The message itself doesn't make that clear, since a "meta" isn't a defined term as far as I know. How about "Pattern variable does not match any non-terminal in <language-name>"?

**Comment by schuster** [comment]
Oh, now I realize "meta" means "metavariable" (I've been thinking in terms of terminal/non-terminal and overlooked that). Still, it should be spelled out in the error message. That's a general pattern I'm seeing with the error messages: they use internal nicknames for terms and terse descriptions, where they should be fully explained.

**Comment by LeifAndersen** [comment]
Okay, thanks for bringing this up. Can you write down an error message that you would have liked to see here?

Thank you again for these issues.

**Comment by schuster** [comment]
How about this:

<file/line number>: f is not a metavariable in language L.

**Comment by LeifAndersen** [comment]
d543406953c45b0dfda4943ac15380d1469ab834 fixes this issue.

Thank you again for submitting it.
