### ISSUE TITLE
Confusing error for multiple ellipses

### ISSUE THREAD

**Issue by schuster** [nanopass/nanopass-framework-racket#6]
The program in this gist gives the error "unrecognized meta-variable in language L <line break> in: ..."
https://gist.github.com/schuster/2ce5886e5f1c8c31558e

I assume Nanopass must only support at most one ellipsis per list. If that's the case, can we get a better error message here?

**Comment by LeifAndersen** [comment]
Yup, your assumption is correct. You can only have one ellipses per level in Nanopass. I will fix the error message to say that.

**Comment by LeifAndersen** [comment]
0f233ab03554f331b8ed0c2c1e639baed0cdbd87 fixes this issue.

Thanks again for submitting it.
